package main;




import utils.LookAndFeel;
import utils.UtilsForImages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author admin
 */
public class GeneratorView extends javax.swing.JPanel {
    
    private LookAndFeel lookAndFeel;

    /**
     * Creates new form GeneratorView
     */
    public GeneratorView() {
        initComponents();
        setBgImagesOnLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        crearLabel = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        desplegableContainer = new javax.swing.JPanel();
        desplegableLabel = new javax.swing.JLabel();
        addPregunta = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        addPreguntaLabel = new javax.swing.JLabel();
        hSpace = new javax.swing.JLabel();
        infoIconLabel = new javax.swing.JLabel();
        debugContainer = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(10, 38, 72));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Crea tu simulador teórico");

        crearLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        crearLabel.setForeground(new java.awt.Color(0, 51, 102));
        crearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearLabel.setText("Crear");
        crearLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Tipo de simulador");

        desplegableContainer.setBackground(new java.awt.Color(10, 38, 72));
        desplegableContainer.setMinimumSize(new java.awt.Dimension(95, 17));
        desplegableContainer.setLayout(new java.awt.BorderLayout());

        desplegableLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        desplegableLabel.setForeground(new java.awt.Color(255, 255, 255));
        desplegableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desplegableLabel.setText("Ahora aprendo");
        desplegableLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desplegableLabel.setFocusable(false);
        desplegableLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        desplegableContainer.add(desplegableLabel, java.awt.BorderLayout.CENTER);

        addPregunta.setBackground(new java.awt.Color(10, 38, 72));
        addPregunta.setMinimumSize(new java.awt.Dimension(95, 0));
        addPregunta.setPreferredSize(new java.awt.Dimension(95, 100));
        addPregunta.setLayout(new javax.swing.BoxLayout(addPregunta, javax.swing.BoxLayout.LINE_AXIS));

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Añadir pregunta");
        addPregunta.add(label3);

        addPreguntaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPreguntaLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        addPreguntaLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        addPreguntaLabel.setPreferredSize(new java.awt.Dimension(20, 20));
        addPregunta.add(addPreguntaLabel);

        hSpace.setMaximumSize(new java.awt.Dimension(10, 20));
        hSpace.setMinimumSize(new java.awt.Dimension(10, 20));
        hSpace.setPreferredSize(new java.awt.Dimension(10, 20));
        addPregunta.add(hSpace);

        infoIconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoIconLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        infoIconLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        infoIconLabel.setPreferredSize(new java.awt.Dimension(20, 20));
        addPregunta.add(infoIconLabel);

        debugContainer.setBackground(new java.awt.Color(10, 38, 72));

        label4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 153, 0));
        label4.setText("El simulador no tiene preguntas");

        javax.swing.GroupLayout debugContainerLayout = new javax.swing.GroupLayout(debugContainer);
        debugContainer.setLayout(debugContainerLayout);
        debugContainerLayout.setHorizontalGroup(
            debugContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debugContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );
        debugContainerLayout.setVerticalGroup(
            debugContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debugContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(10, 38, 72));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(debugContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desplegableContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desplegableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(crearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debugContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPregunta;
    private javax.swing.JLabel addPreguntaLabel;
    private javax.swing.JLabel crearLabel;
    private javax.swing.JPanel debugContainer;
    private javax.swing.JPanel desplegableContainer;
    private javax.swing.JLabel desplegableLabel;
    private javax.swing.JLabel hSpace;
    private javax.swing.JLabel infoIconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables

    private void setBgImagesOnLabels() {
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, desplegableLabel, "Desplegable_Off.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, crearLabel, "Boton_Off.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, infoIconLabel, "Info_Off.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, addPreguntaLabel, "Mas_Off.png");
           
    }
}
