/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import models.Pregunta;
import models.SimuladorTipo;
import services.ComportamientoService;
import services.SimuladorService;
import utils.Utils;

/**
 *
 * @author admin
 */
public class DesplegableView extends javax.swing.JPanel {
    
    private SimuladorService simuladorService = SimuladorService.getInstance();
    private List<SimuladorTipo> listaSimuladores = new ArrayList<>();
    private int cantidadSimuladores;
    private final int simuladorLabelTamaño = 30;
    private final int simuladorLabelPadding = 2;
    

    /**
     * Creates new form DesplegableView
     */
    public DesplegableView() {
        initComponents();
        
        this.simuladorService.cargarSimuladores();
        listaSimuladores = this.simuladorService.getSimuladoresList();
        setSimuladoresTitulo();
    }

    public int getCantidadSimuladores() {
        return cantidadSimuladores;
    }

    public int getSimuladorLabelTamaño() {
        return simuladorLabelTamaño;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(10, 38, 72));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(136, 140, 142)));

        btnContainer.setBackground(new java.awt.Color(10, 38, 72));

        javax.swing.GroupLayout btnContainerLayout = new javax.swing.GroupLayout(btnContainer);
        btnContainer.setLayout(btnContainerLayout);
        btnContainerLayout.setHorizontalGroup(
            btnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        btnContainerLayout.setVerticalGroup(
            btnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnContainer;
    // End of variables declaration//GEN-END:variables

      

    private void setSimuladoresTitulo() {
        // Limpiar el panel de contenedor
        btnContainer.removeAll();
        btnContainer.setLayout(new javax.swing.BoxLayout(btnContainer, javax.swing.BoxLayout.Y_AXIS)); // Asegura un layout adecuado

        for (int i = 0; i < listaSimuladores.size(); i++) {
            SimuladorTipo simulador = listaSimuladores.get(i);
            cantidadSimuladores = listaSimuladores.size();
            // Crear un nuevo JLabel para cada nombre de simulador
            JLabel simuladorLabel = new JLabel(simulador.getName());
            System.out.println("Agregando simulador: " + simulador.getName());

            // Configuración del estilo para el JLabel
            simuladorLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // Fuente tamaño 14
            simuladorLabel.setForeground(new java.awt.Color(255, 255, 255)); // Texto blanco
            simuladorLabel.setBackground(new java.awt.Color(10,38,72));
            simuladorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Padding
            simuladorLabel.setOpaque(true);
            simuladorLabel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, simuladorLabelTamaño)); // Esto hará que el JLabel ocupe todo el ancho
            simuladorLabel.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

            // Añadir el evento de clic al JLabel
            simuladorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // Lógica para manejar el clic
                    //System.out.println("Simulador en Comportamiento: " + simulador.getsimuladorRuta());
                    ComportamientoService.actualizaVistaPreguntas(simulador.getName());
                }

                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    simuladorLabel.setBackground(new java.awt.Color(200, 200, 200)); // Color al pasar el mouse
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    simuladorLabel.setBackground(new java.awt.Color(10,38,72)); // Restaurar color de fondo
                }


            });

            // Agregar el JLabel al contenedor de botones
            btnContainer.add(simuladorLabel);
        }

        // Actualizar la interfaz para reflejar los cambios
        btnContainer.revalidate();
        btnContainer.repaint();
        System.out.println("cantidad de simuladores: " + cantidadSimuladores);
    }
}
