package views;




import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import services.ComportamientoService;
import utils.LookAndFeel;
import utils.UtilsForImages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author admin
 */
public class GeneratorView extends javax.swing.JPanel {
    
    private LookAndFeel lookAndFeel;
    private boolean checkImage = true;
    DesplegableView desplegable = new DesplegableView();
    

    /**
     * Creates new form GeneratorView
     */
    public GeneratorView() {
        initComponents();
        myInitComponents();
        setBgImagesOnLabels();
        setDesplegable();
        
        ComportamientoService.setGeneratorView(this);
        
    }

    public JPanel getPreguntasContainer() {
        return preguntasContainer;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tituloContainer = new javax.swing.JPanel();
        titulo = new java.awt.Label();
        tipoContainer = new javax.swing.JPanel();
        tipoTitulo = new java.awt.Label();
        desplegableContainer = new javax.swing.JPanel();
        desplegableLabel = new javax.swing.JLabel();
        modalContainer = new javax.swing.JPanel();
        scrollContainer = new javax.swing.JScrollPane();
        preguntasContainer = new javax.swing.JPanel();
        addPregunta = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        addPreguntaLabel = new javax.swing.JLabel();
        hSpace = new javax.swing.JLabel();
        infoIconLabel = new javax.swing.JLabel();
        crearContainer = new javax.swing.JPanel();
        crearLabel = new javax.swing.JLabel();
        debugContainer = new javax.swing.JPanel();
        label4 = new java.awt.Label();

        setBackground(new java.awt.Color(10, 38, 72));
        setMaximumSize(new java.awt.Dimension(430, 932));
        setMinimumSize(new java.awt.Dimension(430, 932));
        setPreferredSize(new java.awt.Dimension(430, 932));
        setLayout(new java.awt.GridBagLayout());

        tituloContainer.setBackground(new java.awt.Color(10, 38, 72));

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Crea tu simulador teórico");

        javax.swing.GroupLayout tituloContainerLayout = new javax.swing.GroupLayout(tituloContainer);
        tituloContainer.setLayout(tituloContainerLayout);
        tituloContainerLayout.setHorizontalGroup(
            tituloContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tituloContainerLayout.setVerticalGroup(
            tituloContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(tituloContainer, gridBagConstraints);

        tipoContainer.setBackground(new java.awt.Color(10, 38, 72));

        tipoTitulo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tipoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tipoTitulo.setText("Tipo de simulador");

        javax.swing.GroupLayout tipoContainerLayout = new javax.swing.GroupLayout(tipoContainer);
        tipoContainer.setLayout(tipoContainerLayout);
        tipoContainerLayout.setHorizontalGroup(
            tipoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tipoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        tipoContainerLayout.setVerticalGroup(
            tipoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(tipoContainer, gridBagConstraints);

        desplegableContainer.setBackground(new java.awt.Color(10, 38, 72));
        desplegableContainer.setMinimumSize(new java.awt.Dimension(400, 80));
        desplegableContainer.setPreferredSize(new java.awt.Dimension(404, 250));

        desplegableLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        desplegableLabel.setForeground(new java.awt.Color(255, 255, 255));
        desplegableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desplegableLabel.setText("Ahora aprendo");
        desplegableLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        desplegableLabel.setFocusable(false);
        desplegableLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        desplegableLabel.setMaximumSize(new java.awt.Dimension(400, 50));
        desplegableLabel.setMinimumSize(new java.awt.Dimension(400, 50));
        desplegableLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        desplegableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desplegableLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout desplegableContainerLayout = new javax.swing.GroupLayout(desplegableContainer);
        desplegableContainer.setLayout(desplegableContainerLayout);
        desplegableContainerLayout.setHorizontalGroup(
            desplegableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desplegableContainerLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(desplegableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desplegableContainerLayout.setVerticalGroup(
            desplegableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desplegableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desplegableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(desplegableContainer, gridBagConstraints);

        modalContainer.setBackground(new java.awt.Color(10, 38, 72));
        modalContainer.setMinimumSize(new java.awt.Dimension(380, 300));
        modalContainer.setPreferredSize(new java.awt.Dimension(350, 50));

        javax.swing.GroupLayout modalContainerLayout = new javax.swing.GroupLayout(modalContainer);
        modalContainer.setLayout(modalContainerLayout);
        modalContainerLayout.setHorizontalGroup(
            modalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        modalContainerLayout.setVerticalGroup(
            modalContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(modalContainer, gridBagConstraints);

        scrollContainer.setHorizontalScrollBar(null);
        scrollContainer.setMinimumSize(new java.awt.Dimension(404, 400));
        scrollContainer.setName(""); // NOI18N

        preguntasContainer.setBackground(new java.awt.Color(10, 38, 72));
        preguntasContainer.setMinimumSize(new java.awt.Dimension(280, 900));
        preguntasContainer.setPreferredSize(new java.awt.Dimension(280, 900));
        preguntasContainer.setLayout(new javax.swing.BoxLayout(preguntasContainer, javax.swing.BoxLayout.Y_AXIS));
        scrollContainer.setViewportView(preguntasContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        add(scrollContainer, gridBagConstraints);

        addPregunta.setBackground(new java.awt.Color(10, 38, 72));
        addPregunta.setMinimumSize(new java.awt.Dimension(95, 0));
        addPregunta.setPreferredSize(new java.awt.Dimension(95, 100));
        addPregunta.setLayout(new javax.swing.BoxLayout(addPregunta, javax.swing.BoxLayout.LINE_AXIS));

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Añadir pregunta");
        addPregunta.add(label3);

        addPreguntaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPreguntaLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        addPreguntaLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        addPreguntaLabel.setPreferredSize(new java.awt.Dimension(20, 20));
        addPregunta.add(addPreguntaLabel);

        hSpace.setMaximumSize(new java.awt.Dimension(10, 20));
        hSpace.setMinimumSize(new java.awt.Dimension(10, 20));
        hSpace.setPreferredSize(new java.awt.Dimension(10, 20));
        addPregunta.add(hSpace);

        infoIconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoIconLabel.setMaximumSize(new java.awt.Dimension(20, 20));
        infoIconLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        infoIconLabel.setPreferredSize(new java.awt.Dimension(20, 20));
        addPregunta.add(infoIconLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 298;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(addPregunta, gridBagConstraints);

        crearContainer.setBackground(new java.awt.Color(10, 38, 72));
        crearContainer.setMinimumSize(new java.awt.Dimension(380, 76));

        crearLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        crearLabel.setForeground(new java.awt.Color(0, 51, 102));
        crearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearLabel.setText("Crear");
        crearLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout crearContainerLayout = new javax.swing.GroupLayout(crearContainer);
        crearContainer.setLayout(crearContainerLayout);
        crearContainerLayout.setHorizontalGroup(
            crearContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        crearContainerLayout.setVerticalGroup(
            crearContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(crearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(crearContainer, gridBagConstraints);

        debugContainer.setBackground(new java.awt.Color(10, 38, 72));

        label4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 153, 0));
        label4.setText("El simulador no tiene preguntas");

        javax.swing.GroupLayout debugContainerLayout = new javax.swing.GroupLayout(debugContainer);
        debugContainer.setLayout(debugContainerLayout);
        debugContainerLayout.setHorizontalGroup(
            debugContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debugContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        debugContainerLayout.setVerticalGroup(
            debugContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(debugContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(debugContainer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void desplegableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplegableLabelMouseClicked
        if (checkImage) {      
        UtilsForImages.setImageOnComponentAndSetResizeEvent(this, desplegableLabel, "Desplegable_Off.png");
        modalContainer.setVisible(true);
        int alturaModal = desplegable.getCantidadSimuladores() * desplegable.getSimuladorLabelTamaño();
        modalContainer.setMinimumSize(new java.awt.Dimension(393, alturaModal)); // Cambia el tamaño preferido
    } else {
        UtilsForImages.setImageOnComponentAndSetResizeEvent(this, desplegableLabel, "Desplegable_On.png");
        modalContainer.setVisible(false);
        modalContainer.setMinimumSize(new java.awt.Dimension(393, 54)); // Cambia el tamaño preferido
    }
        modalContainer.revalidate(); // Notifica al layout que el tamaño ha cambiado
        modalContainer.repaint();   // Redibuja el contenedor
        
        desplegableContainer.revalidate();
        desplegableContainer.repaint();
        checkImage = !checkImage;   
    }//GEN-LAST:event_desplegableLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPregunta;
    private javax.swing.JLabel addPreguntaLabel;
    private javax.swing.JPanel crearContainer;
    private javax.swing.JLabel crearLabel;
    private javax.swing.JPanel debugContainer;
    private javax.swing.JPanel desplegableContainer;
    private javax.swing.JLabel desplegableLabel;
    private javax.swing.JLabel hSpace;
    private javax.swing.JLabel infoIconLabel;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JPanel modalContainer;
    private javax.swing.JPanel preguntasContainer;
    private javax.swing.JScrollPane scrollContainer;
    private javax.swing.JPanel tipoContainer;
    private java.awt.Label tipoTitulo;
    private java.awt.Label titulo;
    private javax.swing.JPanel tituloContainer;
    // End of variables declaration//GEN-END:variables

    private void setBgImagesOnLabels() {
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, desplegableLabel, "Desplegable_On.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, crearLabel, "Boton_Off.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, infoIconLabel, "Info_Off.png");
         UtilsForImages.setImageOnComponentAndSetResizeEvent(this, addPreguntaLabel, "Mas_Off.png");
           
    }

    private void setDesplegable() {
    modalContainer.setLayout(new java.awt.BorderLayout()); // Configura el layout
    modalContainer.add(desplegable, java.awt.BorderLayout.CENTER); // Agrega el componente
    modalContainer.revalidate(); // Refresca el contenedor
    modalContainer.repaint(); // Vuelve a dibujar
}

    private void myInitComponents() {
        // Configuración inicial
        desplegableContainer.setMaximumSize(new java.awt.Dimension(400, Integer.MAX_VALUE));
        scrollContainer.getVerticalScrollBar().setPreferredSize(new java.awt.Dimension(5, 0));
        scrollContainer.getVerticalScrollBar().setBackground(Color.DARK_GRAY);  // Fondo oscuro
        scrollContainer.getVerticalScrollBar().setUnitIncrement(16);  // Incremento más rápido
 // Barra vertical fina
        //scrollContainer.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 5)); // Bar

        desplegable.setVisible(false); // Asegúrate de que el modal no sea visible inicialmente
        modalContainer.add(desplegable); // Agrega el modal a su contenedor
        modalContainer.setVisible(false);

        // Listener para el label
        desplegableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleDesplegable();
            }
        });
    }
    private void toggleDesplegable() {
        boolean isCurrentlyVisible = desplegable.isVisible();
        desplegable.setVisible(!isCurrentlyVisible); // Cambia la visibilidad
        modalContainer.revalidate(); // Actualiza el contenedor
        modalContainer.repaint();
    }
}
