/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author admin
 */
public class PreguntaView extends javax.swing.JPanel {

    /**
     * Creates new form PreguntaView
     */
    public PreguntaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPregunta = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        hSpace = new javax.swing.JLabel();
        borrarPreguntaLabel = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        preguntaLabel = new javax.swing.JTextField();
        correctaLabel = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        incorrectaLabel1 = new javax.swing.JTextField();
        incorrectaLabel2 = new javax.swing.JTextField();
        incorrectaLabel3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(10, 38, 72));

        addPregunta.setBackground(new java.awt.Color(10, 38, 72));
        addPregunta.setMinimumSize(new java.awt.Dimension(95, 0));
        addPregunta.setPreferredSize(new java.awt.Dimension(95, 100));
        addPregunta.setLayout(new javax.swing.BoxLayout(addPregunta, javax.swing.BoxLayout.LINE_AXIS));

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Pregunta");
        addPregunta.add(label3);

        hSpace.setMaximumSize(new java.awt.Dimension(10, 20));
        hSpace.setMinimumSize(new java.awt.Dimension(10, 20));
        hSpace.setPreferredSize(new java.awt.Dimension(10, 20));
        addPregunta.add(hSpace);

        borrarPreguntaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarPreguntaLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        borrarPreguntaLabel.setMinimumSize(new java.awt.Dimension(15, 15));
        borrarPreguntaLabel.setName(""); // NOI18N
        borrarPreguntaLabel.setPreferredSize(new java.awt.Dimension(15, 15));
        addPregunta.add(borrarPreguntaLabel);

        label1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Respuesta correcta");

        preguntaLabel.setBackground(new java.awt.Color(117, 113, 113));
        preguntaLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        preguntaLabel.setForeground(new java.awt.Color(255, 255, 255));
        preguntaLabel.setText("  Ejemplo");
        preguntaLabel.setBorder(null);
        preguntaLabel.setOpaque(true);
        preguntaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntaLabelActionPerformed(evt);
            }
        });

        correctaLabel.setBackground(new java.awt.Color(117, 113, 113));
        correctaLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        correctaLabel.setForeground(new java.awt.Color(255, 255, 255));
        correctaLabel.setText("  Ejemplo correcta");
        correctaLabel.setBorder(null);
        correctaLabel.setOpaque(true);
        correctaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctaLabelActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Respuestas incorrectas");

        incorrectaLabel1.setBackground(new java.awt.Color(117, 113, 113));
        incorrectaLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        incorrectaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel1.setText("  Ejemplo incorrecta 1");
        incorrectaLabel1.setBorder(null);
        incorrectaLabel1.setOpaque(true);
        incorrectaLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectaLabel1ActionPerformed(evt);
            }
        });

        incorrectaLabel2.setBackground(new java.awt.Color(117, 113, 113));
        incorrectaLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        incorrectaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel2.setText("  Ejemplo incorrecta 2");
        incorrectaLabel2.setBorder(null);
        incorrectaLabel2.setOpaque(true);
        incorrectaLabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectaLabel2ActionPerformed(evt);
            }
        });

        incorrectaLabel3.setBackground(new java.awt.Color(117, 113, 113));
        incorrectaLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        incorrectaLabel3.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel3.setText("  Ejemplo incorrecta 3");
        incorrectaLabel3.setBorder(null);
        incorrectaLabel3.setOpaque(true);
        incorrectaLabel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incorrectaLabel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(correctaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(preguntaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(incorrectaLabel1)
                    .addComponent(incorrectaLabel2)
                    .addComponent(incorrectaLabel3))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(addPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(preguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correctaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incorrectaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incorrectaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incorrectaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(addPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void preguntaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntaLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preguntaLabelActionPerformed

    private void correctaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctaLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctaLabelActionPerformed

    private void incorrectaLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectaLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incorrectaLabel1ActionPerformed

    private void incorrectaLabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectaLabel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incorrectaLabel2ActionPerformed

    private void incorrectaLabel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incorrectaLabel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incorrectaLabel3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPregunta;
    private javax.swing.JLabel borrarPreguntaLabel;
    private javax.swing.JTextField correctaLabel;
    private javax.swing.JLabel hSpace;
    private javax.swing.JTextField incorrectaLabel1;
    private javax.swing.JTextField incorrectaLabel2;
    private javax.swing.JTextField incorrectaLabel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField preguntaLabel;
    // End of variables declaration//GEN-END:variables
}
