/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class PreguntaView extends javax.swing.JPanel {

    /**
     * Creates new form PreguntaView
     */
    public PreguntaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPregunta = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        preguntaLabel = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        correctaLabel = new javax.swing.JTextArea();
        label2 = new java.awt.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        incorrectaLabel1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        incorrectaLabel2 = new javax.swing.JTextArea();
        borrarPreguntaLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        incorrectaLabel3 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(37, 51, 66));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addPregunta.setBackground(new java.awt.Color(77, 117, 165));
        addPregunta.setMinimumSize(new java.awt.Dimension(95, 0));
        addPregunta.setPreferredSize(new java.awt.Dimension(95, 100));
        addPregunta.setLayout(new java.awt.GridLayout(1, 0));

        label3.setBackground(new java.awt.Color(37, 51, 66));
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setMinimumSize(new java.awt.Dimension(20, 20));
        label3.setText("Pregunta");
        addPregunta.add(label3);

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        preguntaLabel.setBackground(new java.awt.Color(71, 81, 92));
        preguntaLabel.setColumns(20);
        preguntaLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        preguntaLabel.setForeground(new java.awt.Color(255, 255, 255));
        preguntaLabel.setRows(5);
        preguntaLabel.setText("PreguntaEjemplo");
        preguntaLabel.setBorder(null);
        jScrollPane2.setViewportView(preguntaLabel);

        label1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Respuesta correcta");

        correctaLabel.setBackground(new java.awt.Color(71, 81, 92));
        correctaLabel.setColumns(20);
        correctaLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        correctaLabel.setForeground(new java.awt.Color(255, 255, 255));
        correctaLabel.setRows(5);
        correctaLabel.setText("CorrectaLabel");
        correctaLabel.setBorder(null);
        jScrollPane1.setViewportView(correctaLabel);

        label2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Respuestas incorrectas");

        incorrectaLabel1.setBackground(new java.awt.Color(71, 81, 92));
        incorrectaLabel1.setColumns(20);
        incorrectaLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        incorrectaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel1.setRows(5);
        incorrectaLabel1.setText("InorrectaLabel1");
        incorrectaLabel1.setBorder(null);
        jScrollPane3.setViewportView(incorrectaLabel1);

        incorrectaLabel2.setBackground(new java.awt.Color(71, 81, 92));
        incorrectaLabel2.setColumns(20);
        incorrectaLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        incorrectaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel2.setRows(5);
        incorrectaLabel2.setText("InorrectaLabel1");
        incorrectaLabel2.setBorder(null);
        jScrollPane4.setViewportView(incorrectaLabel2);

        borrarPreguntaLabel.setBackground(new java.awt.Color(37, 51, 66));
        borrarPreguntaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarPreguntaLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        borrarPreguntaLabel.setMinimumSize(new java.awt.Dimension(15, 15));
        borrarPreguntaLabel.setName(""); // NOI18N
        borrarPreguntaLabel.setPreferredSize(new java.awt.Dimension(15, 15));

        incorrectaLabel3.setBackground(new java.awt.Color(71, 81, 92));
        incorrectaLabel3.setColumns(20);
        incorrectaLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        incorrectaLabel3.setForeground(new java.awt.Color(255, 255, 255));
        incorrectaLabel3.setRows(5);
        incorrectaLabel3.setText("InorrectaLabel1");
        incorrectaLabel3.setBorder(null);
        jScrollPane5.setViewportView(incorrectaLabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(borrarPreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5)))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(addPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(241, 241, 241)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(borrarPreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(addPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPregunta;
    private javax.swing.JLabel borrarPreguntaLabel;
    private javax.swing.JTextArea correctaLabel;
    private javax.swing.JTextArea incorrectaLabel1;
    private javax.swing.JTextArea incorrectaLabel2;
    private javax.swing.JTextArea incorrectaLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextArea preguntaLabel;
    // End of variables declaration//GEN-END:variables

    public JTextArea getCorrectaLabel() {
        return correctaLabel;
    }

    public void setCorrectaLabel(JTextArea correctaLabel) {
        this.correctaLabel = correctaLabel;
    }

    public JTextArea getIncorrectaLabel1() {
        return incorrectaLabel1;
    }

    public void setIncorrectaLabel1(JTextArea incorrectaLabel1) {
        this.incorrectaLabel1 = incorrectaLabel1;
    }

    public JTextArea getIncorrectaLabel2() {
        return incorrectaLabel2;
    }

    public void setIncorrectaLabel2(JTextArea incorrectaLabel2) {
        this.incorrectaLabel2 = incorrectaLabel2;
    }

    public JTextArea getIncorrectaLabel3() {
        return incorrectaLabel3;
    }

    
    public JTextArea getPreguntaLabel() {
        return preguntaLabel;
    }
    
    

    public void setIncorrectaLabel3(JTextArea incorrectaLabel3) {
        this.incorrectaLabel3 = incorrectaLabel3;
    }

    public void setPreguntaLabel(JTextArea preguntaLabel) {
        this.preguntaLabel = preguntaLabel;
    }

    

}
